server:
  port: 8080  # 指定端口

spring:
  resource:
    static-locations: classpath:/static/ #静态资源位置
  redis:
    host: 127.0.0.1
    port: 6379
    password: ''
  datasource:
    url: jdbc:mysql://172.31.0.191:32768/data?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    throw-exception-if-no-handler-found: true  # 启用404详细错误
  web:
    resources:
      add-mappings: false

logging:
  level:
    root: debug  # 全局日志级别
    com.henu.ocr: trace  # 项目包日志细节
    org.springframework.jdbc: debug  # 显示SQL日志
    # application.yml
#jeecg:
#  activiti:
#    database-schema-update: true # 自动生成工作流表
#    check-process-definitions: true # 检查流程定义
#    process-definition-location: classpath:/processes/*.bpmn20.xml # 流程文件路径


# MyBatis-Plus 配置
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml  # XML映射文件路径
  type-aliases-package: com.henu.ocr.entity  # 实体类包路径
  configuration:
    map-underscore-to-camel-case: true  # 下划线转驼峰
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # 控制台打印SQL
  global-config:
    db-config:
      id-type: auto  # 主键自增策略
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
security:
  jwt:
#    secret:
    expiration: 480